@startuml
{{#.}}
group {{code}}:{{#triggers}}{{.}}, {{/triggers}}
    {{#steps}}
    "{{from}}" --> "{{to}}": {{value}}
    {{/steps}}
    note across: {{#results}}{{.}}, {{/results}}
end
{{/.}}
@enduml
